#!/bin/bash

skipTests=false
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
        -r)
            rebuild=true
            shift
        ;;
        -s)
            skipTests=true
            shift
        ;;
        -jlink)
            shift
            jlinkPath="$1"
            shift
        ;;
        -maplePath)
            shift
            maplePath="$1"
            shift
        ;;
        -mapleLibraryPath)
            shift
            mapleLibraryPath="$1"
            shift
        ;;
        *)
            break
        ;;
esac
done

if [ ! -f target/bbcc.jar ];
then
    rebuild=true
    if [ -z "$skipTests" ]; 
    then
        skipTests=true
    fi
fi


# Maple and Mathematica variables
if [ -z "$jlinkPath" ];
then
    jlinkPath="/Applications/Mathematica.app/SystemFiles/Links/JLink/JLink.jar"
fi

if [ -z "$maplePath" ];
then
    maplePath="/Library/Frameworks/Maple.framework/Versions/18"
fi

if [ -z "$mapleLibraryPath" ];
then
    mapleLibraryPath="/Library/Frameworks/Maple.framework/Versions/18/bin.APPLE_UNIVERSAL_OSX"
fi

classpath="${jlinkPath}:${maplePath}/java/jopenmaple.jar:${maplePath}/java/externalcall.jar:target/bbcc.jar"

export MAPLE="$maplePath"
os=`uname`
case $os in
    Darwin)
        export DYLD_LIBRARY_PATH="$mapleLibraryPath"
    ;;
    Linux)
        export LD_LIBRARY_PATH="$mapleLibraryPath"
    ;;
    *)
       echo "Unknown OS."
       exit 1
    ;;
esac


if [ ! -z "$rebuild" ]; 
then
    dSkipTests=""
    if [[ ${skipTests} == true ]];
    then
        dSkipTests="-DskipTests"
    fi

    dJLink=""
    if [ ! -z "$jlinkPath" ];
    then
        dJLink="\"-Djlink=${jlinkPath}\""
    fi
    echo mvn clean install assembly:single ${dSkipTests} -Djlink=${jlinkPath} -Djopenmaple1=${maplePath}/java/jopenmaple.jar -Djopenmaple2=${maplePath}/java/externalcall.jar
    printf "\n"
    mvn clean install assembly:single ${dSkipTests} -Djlink=${jlinkPath} -Djopenmaple1=${maplePath}/java/jopenmaple.jar -Djopenmaple2=${maplePath}/java/externalcall.jar
fi


# printf "\n\n\n\n\n"
# echo java -Xmx6g -Xms5g -XX:+AggressiveOpts -cp ${classpath} cc.redberry.groovy.feyncalc.pairedchi.cli.Main "$@"
# printf "\n"

java -Xmx6g -Xms5g -XX:+AggressiveOpts -Djava.library.path="$mapleLibraryPath" -cp ${classpath} cc.redberry.groovy.feyncalc.pairedchi.cli.Main "$@"


