#!/bin/bash

outputPath="output"
list=(
	"scalar" "scalar" "${outputPath}/ss.redberry"
	"scalar" "axial" "${outputPath}/sa.redberry"
	"scalar" "tensor" "${outputPath}/st.redberry"
	"axial" "scalar" "${outputPath}/as.redberry" 
	"axial" "axial" "${outputPath}/aa.redberry"
	"axial" "tensor" "${outputPath}/at.redberry"
	"tensor" "scalar" "${outputPath}/ts.redberry" 
	"tensor" "axial" "${outputPath}/ta.redberry"
	"tensor" "tensor" "${outputPath}/tt.redberry"
	)

jlinkArg="$@"
export jlinkArg

progressFile="${outputPath}/chiProgress"
function chiProcess(){
	echo "./bbcc `echo "${jlinkArg}"` chi -f `echo "$@"` > `echo "${3}Progress"`"
	./bbcc `echo "${jlinkArg}"` chi -f `echo "$@"` > `echo "${3}Progress"`
}

export -f chiProcess
export list
echo ${list[@]} | tr ' ' '\n' | parallel --gnu -N 3 chiProcess {1} {2} {3}