#!/bin/bash

outputPath="output"
list=("scalar" "${outputPath}/s.redberry" "axial" "${outputPath}/a.redberry" "tensor" "${outputPath}/t.redberry")

jlinkArg="$@"
export jlinkArg

function ccProcess(){
	echo "./bbcc `echo "${jlinkArg}"` cc -f `echo "$@"` > `echo "${2}Progress"`"
	./bbcc `echo "${jlinkArg}"` cc -f `echo "$@"` > `echo "${2}Progress"`
}

export -f ccProcess
export list
echo ${list[@]} | tr ' ' '\n' | parallel --gnu -N 2 ccProcess "$@" {1} {2}