#!/bin/bash

outputPath="output"
list=("scalar" "${outputPath}/ward_s.redberry" "axial" "${outputPath}/ward_a.redberry" "tensor" "${outputPath}/ward_t.redberry")

jlinkArg="$@"
export jlinkArg

function ccwProcess(){
	echo "./bbcc `echo "${jlinkArg}"` cc -f --ward `echo "$@"` > `echo "${2}Progress"`"
	./bbcc `echo "${jlinkArg}"` cc -f --ward `echo "$@"` > `echo "${2}Progress"`
}

export -f ccwProcess
export list
echo ${list[@]} | tr ' ' '\n' | parallel --gnu -N 2 ccwProcess {1} {2}